logging:
  level:
    root: INFO
spring:
  application:
    name: "IBIS Laboratory Service"
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://laboratory-db:5434/postgresDB"
    username: "student"
    password: "student"
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
server:
  port: 8083
  servlet:
    context-path: "/api"
jwt.secret.key: "secret_key"


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,loggers
  endpoint:
    info:
      enabled: 'true'


user-service-url: "http://user-service:8081/api/"