global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "user-service"
    metrics_path: "api/user/actuator/prometheus"
    static_configs:
      - targets: ["bolnica-2.k8s.elab.rs"]
  - job_name: "patient-service"
    metrics_path: "api/patient/actuator/prometheus"
    static_configs:
      - targets: ["bolnica-2.k8s.elab.rs"]

  - job_name: "laboratory-service"
    metrics_path: "api/lab/actuator/prometheus"
    static_configs:
      - targets: ["bolnica-2.k8s.elab.rs"]